name: firecrawl-master

x-common-service: &common-service
  build: apps/api
  networks:
    - backend
  environment:
    - REDIS_URL=redis://redis:6379
    - REDIS_RATE_LIMIT_URL=redis://redis:6379
    - PORT=3002
    - NUM_WORKERS_PER_QUEUE=2
    - BULL_AUTH_KEY=possumden
    - HOST=0.0.0.0
    - LOGGING_LEVEL=info
    - MAX_RAM=0.95
    - MAX_CPU=0.95
  extra_hosts:
    - "host.docker.internal:host-gateway"
services:
  puppeteer-service:
    image: trieve/puppeteer-service-ts
    build:
      context: ./apps/puppeteer-service-ts/
      dockerfile: Dockerfile
    environment:
      - PORT=3100
      - MAX_CONCURRENCY=5
    networks:
      - backend
    # Expose the Playwright/Puppeteer service to external connections
    ports:
      - "3100:3000"
  api:
    image: trieve/firecrawl
    <<: *common-service
    depends_on:
      - redis
      - puppeteer-service
    ports:
      - "3002:3002"
    command: ["pnpm", "run", "start:production"]
  worker:
    <<: *common-service
    depends_on:
      - redis
      - puppeteer-service
      - api
    command: ["pnpm", "run", "workers"]
    environment:
      - WORKER_ID=${WORKER_NAME:-main-worker}
  redis:
    image: redis:alpine
    networks:
      - backend
    # Expose Redis to external connections with password protection
    command: redis-server --bind 0.0.0.0
    ports:
      - "6380:6379"
    # Add volume for data persistence
    volumes:
      - redis_data:/data
networks:
  backend:
    driver: bridge
volumes:
  redis_data:
